name: Update Homebrew Tap
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    - name: Update scalar Cask
      uses: mjcheetham/update-homebrew@v1.1
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: gaborcsardi/rim
        name: gaborcsardi/rim
        type: cask
        releaseTag: v0.2.0
        releaseAsset: rim-(.*)-macOS-.*[.]pkg
        alwaysUsePullRequest: true
