name: Update Homebrew Tap
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    - id: version
      name: Compute version number
      run: |
        echo "::set-output name=result::$(grep '^version' Cargo.toml | tr -cd '0-9.')"

    - name: Update scalar Cask
      uses: mjcheetham/update-homebrew@v1.1
      with:
        name: gaborcsardi/rim
        releaseTag: v0.2.0
        releaseAsset: /^rim-(?<version>.*)-macOS-.*[.]pkg$/
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: gaborcsardi/rim
        type: cask
        version: ${{ steps.version.outputs.result }}
        alwaysUsePullRequest: true
