name: Update Homebrew Tap
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - id: version
      name: Compute version number
      run: |
        echo "::set-output name=result::$(grep '^version' Cargo.toml | tr -cd '0-9.')"
    - id: hash
      name: Compute release asset hash
      uses: mjcheetham/asset-hash@v1
      with:
        tag: v0.2.0
        asset: /rim-(.*)\.pkg/
        hash: sha256
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update scalar Cask
      uses: mjcheetham/update-homebrew@v1.1
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: gaborcsardi/rim
        name: gaborcsardi/rim
        type: cask
        version: ${{ steps.version.outputs.result }}
        sha256: ${{ steps.hash.outputs.result }}
        alwaysUsePullRequest: true
